project:
  type: book

book:
  title: "Investigating and Improving the Transparency and Reproducibility of Model-Based Research in Ecology and Conservation"
  author: "Elliot Gould"
  description: "A thesis submitted in total fulfillment for the degree of Doctor of Philosophy at The University of Melbourne in 2023 in the Faculty of Science, School of Ecosystem and Forest Sciences."
  chapters:
    - index.qmd
    - abstract.qmd
    - declaration.qmd
    - acknowledgements.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
  appendices:
    - "A-appA.qmd"
  references: refs.qmd
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. © 2023, Elliot Gould"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"

toc-title: "<b>Sections</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
bibliography: thesisrefs.bib
csl: apa-single-spaced.csl
fig-height: 3.8
fig-width: 6.3
degreetype: Doctor of Philosophy
submitted: 2023
affiliation: School of Ecosystem and Forest Sciences, Faculty of Science
degrees: 'B.Sc., B.A., M.Sc., University of Melbourne'
execute:
  freeze: auto
  echo: false

format:
  html:
    theme:
      - cosmo
      - thesis.scss
    fontsize: 16px
    mainfont: "Merriweather, Georgia, serif"
    code-link: true
  unimelbthesis-pdf:
    keep-tex: false
